In [69]:
import numpy as np
import pandas as pd

In [70]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [71]:
df = pd.read_csv('/content/drive/MyDrive/ML Codes/01_Feature Engineering/04_One_Hot_Encoding/cars.csv')

In [72]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [73]:
df.shape

(8128, 5)

In [74]:
df.describe()

          km_driven  selling_price
count  8.128000e+03   8.128000e+03
mean   6.981951e+04   6.382718e+05
std    5.655055e+04   8.062534e+05
min    1.000000e+00   2.999900e+04
25%    3.500000e+04   2.549990e+05
50%    6.000000e+04   4.500000e+05
75%    9.800000e+04   6.750000e+05
max    2.360457e+06   1.000000e+07

In [75]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [76]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [77]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## **OHE using Sklearn**

In [78]:
from sklearn.preprocessing import OneHotEncoder

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
X = df.iloc[:,0:4]
y = df['selling_price']

In [81]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [82]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [83]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [84]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [85]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 80000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 40000, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Renault', 30000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 10000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Skoda', 125000, 1.0, ..., 1.0, 0.0, 0.0]], dtype=object)

## Top categories and Rare or less Categories items OHE

In [87]:
counts = df['brand'].value_counts()

In [89]:
df['brand'].nunique()
threshold = 100

In [90]:
replace_val = counts[counts<= threshold].index

In [93]:
pd.get_dummies(df['brand'].replace(replace_val, 'uncommon')).sample(7)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
1923,False,False,True,False,False,False,False,False,False,False,False,False,False
374,False,False,False,False,False,False,False,False,False,False,False,False,True
5138,False,True,False,False,False,False,False,False,False,False,False,False,False
129,False,False,False,False,False,False,True,False,False,False,False,False,False
6386,False,False,False,False,False,False,True,False,False,False,False,False,False
6262,False,False,False,False,False,True,False,False,False,False,False,False,False
7034,False,False,False,True,False,False,False,False,False,False,False,False,False