In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [52]:
df = pd.read_csv('/content/drive/MyDrive/ML Codes/01_Feature Engineering/03_Ordinal  encoding/customer.csv')

In [53]:
df.shape

(50, 5)

In [54]:
df.sample(10)

    age  gender   review education purchased
39   76    Male     Poor        PG        No
17   22  Female     Poor        UG       Yes
10   98  Female     Good        UG       Yes
7    60  Female     Poor    School       Yes
27   69  Female     Poor        PG        No
24   16  Female  Average        PG       Yes
37   94    Male  Average        PG       Yes
5    31  Female  Average    School       Yes
29   83  Female  Average        UG       Yes
11   74    Male     Good        UG       Yes

In [55]:
df = df.iloc[:,2:]

In [56]:
df.sample(5)

     review education purchased
48     Good        UG       Yes
26     Poor        PG        No
44  Average        UG        No
24  Average        PG       Yes
7      Poor    School       Yes

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X =df.drop(columns='purchased',axis=1)
y =df['purchased']

In [59]:
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2)

In [60]:
X_train.sample(5)

     review education
25     Good    School
6      Good    School
13  Average    School
34  Average    School
43     Poor        PG

In [61]:
from sklearn.preprocessing import OrdinalEncoder

In [62]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [63]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [64]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [65]:
X_train

array([[1., 0.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [1., 2.]])

## Label Encoder

In [66]:
from sklearn.preprocessing import LabelEncoder

In [67]:
le = LabelEncoder()

In [68]:
le.fit(y_train)

LabelEncoder()

In [69]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [70]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [71]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0])